export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INCREASE_ITEMS_COUNT = "INCREASE_ITEMS_COUNT";
export const DECREASE_ITEMS_COUNT = "DECREASE_ITEMS_COUNT";